site_name: Car Parking Detection
theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Model Details: model.md
  - Slot Marking: mark_slots.md
